### ISSUE TITLE
Pressing any key (except for left or right arrow) produces an error

### ISSUE THREAD

**Issue by sjara** [sjara/brainmix#2]
Pressing most keys on the main window produces the error:

``` python
Traceback (most recent call last):
  File "/home/sjara/src/brainmix/brainmix/gui/mainwindow.py", line 227, in keyPressEvent
    self.set_image()
  File "/home/sjara/src/brainmix/brainmix/gui/mainwindow.py", line 68, in set_image
    self.imageViewer.set_image(self.data.get_current_image())
  File "/home/sjara/src/brainmix/brainmix/core/data.py", line 64, in get_current_image
    return self.images[self.currentImage]
IndexError: list index out of range
```

**Comment by sjara** [comment]
The error seems to be due to running set_image() on MainWindow.keyPressEvent() every time, even if the key has not been assigned to anything.
