### ISSUE TITLE
Zooming produces an error

### ISSUE THREAD

**Issue by sjara** [sjara/brainmix#5]
Zoom in and zoom out, either from menu or shortcuts give the error:

``` python
Traceback (most recent call last):
  File "/home/sjara/src/brainmix/brainmix/gui/mainwindow.py", line 177, in slot_zoom_out
    self.alignedViewer.zoom_out()
  File "/home/sjara/src/brainmix/brainmix/gui/image_viewer.py", line 62, in zoom_out
    self.scale_image(0.8)
  File "/home/sjara/src/brainmix/brainmix/gui/image_viewer.py", line 47, in scale_image
    self.imageLabel.resize(self.scaleFactor * self.imageLabel.pixmap().size())
AttributeError: 'NoneType' object has no attribute 'size'
```

**Comment by kpotter** [comment]
This bug has been fixed by testing to see if there is an image loaded before querying it's size.  Not sure if this actually relates to shortcuts however.
